# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'WallMessaging' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WallMessaging

pod 'AFNetworking', '~>2.2'

pod 'SignalR-ObjC'

pod 'SocketRocket', '0.4.2'

  target 'WallMessagingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WallMessagingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
